Ajio Assignment
znsio/getting-started-with-teswiz pull request #43
Opened 2023-02-16 09:57 UTC by MedhaGupta-Ril

2023-02-17 12:22 UTC, Mohammed9901 commented on src/test/java/com/znsio/sample/e2e/screen/ajio/SearchResultsScreen.java
> +        switch(platform) {
Remove instance for android as you have not used in scenario.

2023-02-17 12:23 UTC, Mohammed9901 commented on src/test/java/com/znsio/sample/e2e/screen/web/ajio/ProductDetailScreenWeb.java
> +        webElement.click();
Directly perform the action without creating an instance.

2023-02-17 12:25 UTC, Mohammed9901 commented on src/test/java/com/znsio/sample/e2e/screen/web/ajio/ProductDetailScreenWeb.java
> +        LOGGER.info(String.format("Product size selected '%s'", webElement.getText()));
Avoid using unnecessary loggers, if you have provided assertions in BL.

2023-02-23 12:22 UTC, vishal07111998 commented on src/test/java/com/znsio/sample/e2e/screen/web/ajio/ProductDetailScreenWeb.java
> +    //improve xpath
remove unwanted comments

2023-02-23 12:22 UTC, vishal07111998 commented on src/test/java/com/znsio/sample/e2e/screen/android/ajio/ShoppingCartScreenAndroid.java
> +    private static final String NOT_YET_IMPLEMENTED = " not yet implemented";
remove unused variables

2023-02-23 12:22 UTC, vishal07111998 commented on src/test/java/com/znsio/sample/e2e/screen/android/ajio/ShoppingCartScreenAndroid.java
> +    private static final By byProductBrandId = By.id("com.ril.ajio:id/brandInfo");
package name can be removed

2023-02-23 12:22 UTC, vishal07111998 commented on src/test/java/com/znsio/sample/e2e/screen/android/ajio/ProductDetailScreenAndroid.java
> +    private static final By byProductSizeXpath = By.xpath("//android.widget.TextView[@resource-id = 'com.ril.ajio:id/row_pdp_fixed_size_tv' and @text = '8']");
try to use better locators

2023-02-23 12:24 UTC, vishal07111998 requested changes

2023-02-23 12:24 UTC, vishal07111998 commented on src/test/java/com/znsio/sample/e2e/screen/web/ajio/AjioHomeScreenWeb.java
> +    public SearchResultsScreen searchFor(String product) {
Class Name Can be HomeScreenWeb as package name already contains ajio

2023-02-23 12:25 UTC, vishal07111998 commented
Remove unwanted data, files or directories that you are not using

2023-06-15 12:54 UTC, closed without merging